### ISSUE TITLE
Bot allows reminders in the past

### ISSUE THREAD

**Issue by svierne** [anoadragon453/matrix-reminder-bot#127]
`!remindme before 7 minutes; test` still works for some reason.
It seems to work up to exactly this threshold of 7 minutes.
My timezone is set to `Europe/Berlin`, matching the Docker container.

**Comment by HarHarLinks** [comment]
![image](https://github.com/anoadragon453/matrix-reminder-bot/assets/2803622/97641f0f-3c42-4e27-a078-71cd7bd18056)
seems to be some pytz issue? https://pythonhosted.org/pytz/
