### ISSUE TITLE
wrong "every" reminder syntax fails silently

### ISSUE THREAD

**Issue by HarHarLinks** [anoadragon453/matrix-reminder-bot#168]
command `!every 1h; fail; again` fails silently. nothing in the logs.

**Comment by svierne** [comment]
Does the bot really support `!every`? I was unable to find it in the source code or using `!help reminders`.
`!remindme every 1h; fail; again` fails with an error message, as intended.

**Comment by HarHarLinks** [comment]
I think I might've opened this issue on the basis of watching someone try `!every` which as you say isn't a correct command, yet they believed it was.

I still might've opened it in error, given the bot isn't really supposed to react to commands that don't belong to it. So perhaps let's close this?
