### ISSUE TITLE
Database has become inconsistent

### ISSUE THREAD

**Issue by HarHarLinks** [anoadragon453/matrix-reminder-bot#18]
- still have an old missed reminder (created and missed with f36355ac194f517e5a65357099c081a950f266aa or so) in the format `2020-06-09 11:41:46`, but it won't delete itself :(
- had an otwsu reminder using cron, but the cron column is now empty
- the test reminder that i just added (`!remindme 5s; testerino`) but that seems broken too `testerino|2020-06-11T15:19:38+00:53|||!pmwiththebot:myerver|@myself:myserver|0`. the bot said "yeah i'll remind you" but subsequently didn't, nor did it remove the event. the timestamp seems messed up anyway.

**Comment by anoadragon453** [comment]
> still have an old missed reminder (created and missed with f36355a or so) in the format 2020-06-09 11:41:46, but it won't delete itself :(

Missed reminders will only be deleted if they are not recurring and/or they aren't cron-based.

> had an otwsu reminder using cron, but the cron column is now empty

This is a known bug with a previous commit. It should be fixed now but you may have to recreate the reminder/enter the cron tab into the database manually.

> the test reminder that i just added (!remindme 5s; testerino) but that seems broken too testerino|2020-06-11T15:19:38+00:53|||!pmwiththebot:myerver|@myself:myserver|0. the bot said "yeah i'll remind you" but subsequently didn't, nor did it remove the event. the timestamp seems messed up anyway.

Huh, what is going on with the UTC offset o.O

I'm hoping to rework timezones when fixing #15 which should hopefully eliminate this problem as a side-effect.

**Comment by HarHarLinks** [comment]
> Missed reminders will only be deleted if they are not recurring and/or they aren't cron-based.

this is a simple oneshot

**Comment by anoadragon453** [comment]
Going to close this as there's been a lot of bug fixing with the database since this issue was opened, and as a result I currently don't see any clear, actionable issues here. https://github.com/anoadragon453/matrix-reminder-bot/issues/32 is currently the last known database issue.

Please open a new issue if you still have issues with the database.
