### ISSUE TITLE
Reminders containing special chars don't get deleted from the database

### ISSUE THREAD

**Issue by HarHarLinks** [anoadragon453/matrix-reminder-bot#32]
This issue appears with anoa/matrix-reminder-bot from docker hub, image id `7aea2fd4b12e` (latest at the time of writing). Using sqlite3 database.
Edit: the host system uses en_US.UTF-8 for all locale, but I think it should be the docker container's locales that would apply anyway.

![image](https://user-images.githubusercontent.com/2803622/87031555-95039b80-c1e3-11ea-8886-a28ab7a8a702.png)

"debugging test" gets added and deleted fine. However this is the database after running the commands in the screenshot above:
```
sqlite> select * from reminder;
debugging test,€123üöä|2021-01-10T12:00:00|||!my:room|@my:self|0|Europe/Berlin
```

It looks like some of these special characters mess up the deletion from the database? I seem to remember you can set databases to use certain encoding.
To hunt this down further: The same issue appeared in a reminder containing only `,` and `€`, as well as a possibly related similar issue about one month ago in another message containing `ß` and a number (see also [#matrix-reminder-bot:matrix.org](https://matrix.to/#/!UrnolKvyGxLvrqKFmv:amorgan.xyz/$UKzrSbCtrheL5CZ1xNRxgmq1sDjzgRD9i8STZsySSJw?via=amorgan.xyz&via=matrix.org)).

**Comment by anoadragon453** [comment]
Fixed in https://github.com/anoadragon453/matrix-reminder-bot/commit/9b928a433ff23c5cc659b1f6544cdcffd708d1cc :)
