### ISSUE TITLE
Fractional hours lead to incorrect results

### ISSUE THREAD

**Issue by spantaleev** [anoadragon453/matrix-reminder-bot#37]
`!remindme in 1.5 hours; Test` actually sets a reminder for 5 hours into the future.

Of course, supporting things like `1.2 hours` would be weird (that's most likely 1 hour and 12 minutes), but `1.5 hours` sounds like a common-enough use-case that people would expect to work.

It should be noted that the above also can't be done by specifying `in 1h30m`. That's taken to mean `at 01:30`, which is completely bizarre, but I'm opening another issue for it.

**Comment by anoadragon453** [comment]
The bot uses https://github.com/scrapinghub/dateparser to parse dates and times. I can reproduce your issue, but I suggest you make an issue upstream instead.
