### ISSUE TITLE
Things like "in 1h30m" don't work

### ISSUE THREAD

**Issue by spantaleev** [anoadragon453/matrix-reminder-bot#38]
> - `!remindme in 1h30m; Test`
> - `OK, I will remind you on Jul 23 2020, 01:30!`

The above is taken to mean `at 01:30` and not `in 1 hour and 30 minutes`. Using absolute time when the input starts with `in ..` seems completely wrong.

**Comment by anoadragon453** [comment]
The bot uses https://github.com/scrapinghub/dateparser to parse dates and times. I can reproduce your issue (and found that `in 1h 30m` curiously works), but I suggest you make an issue upstream instead.
