### ISSUE TITLE
Update docker instructions

### ISSUE THREAD

**Issue by HarHarLinks** [anoadragon453/matrix-reminder-bot#4]
Sadly, the instructions [here](https://github.com/anoadragon453/matrix-reminder-bot/tree/master/docker#building-the-image) do not "just work":

```
$ docker build -t anoadragon453/matrix-reminder-bot -f docker/Dockerfile .
Sending build context to Docker daemon  224.3kB
Step 1/11 : ARG PYTHON_VERSION=3.8
Step 2/11 : FROM anoadragon453/matrix-nio:python-${PYTHON_VERSION}
pull access denied for anoadragon453/matrix-nio, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

The obvious reason being that the base image isn't on docker hub and would not be built automatically. I don't know if you can make docker build recursively automatically? You clearly included the `matrix-nio.Dockerfile` to account for this. So my best guess it to add `docker build -t anoadragon453/matrix-nio -f docker/matrix-nio.Dockerfile .` as a pre-command before building the reminder container.

Update: Hm well, you'll need to take care of the `${PYTHON_VERSION}` additionally, so maybe rather:
```
docker build -t anoadragon453/matrix-nio:python-3.8 -f docker/matrix-nio.Dockerfile --build-arg PYTHON_VERSION=3.8 .
```

**Comment by anoadragon453** [comment]
Ah, yes, I haven't actually pushed them yet :upside_down_face: 

Will do so rather soon.

**Comment by anoadragon453** [comment]
Dockerfiles have been rewritten with a further reduction in size, and now actually pushed to Dockerhub :)

The matrix.nio.Dockerfile is actually no longer needed. I'll PR it to [matrix-nio](https://github.com/poljar/matrix-nio) and remove it from this repository sometime tomorrow.
