### ISSUE TITLE
!alarm commands should use "alarm" in the feedback message

### ISSUE THREAD

**Issue by HarHarLinks** [anoadragon453/matrix-reminder-bot#40]
>!alarmme 10m; test
>OK, I will remind you on Jul 24 2020, 23:15!

>!cancelalarm test
>Reminder cancelled.

I think these should say "will alarm you" and "Alarm cancelled" to reflect the distinction.

**Comment by anoadragon453** [comment]
Well, an alarm is just a reminder that fires off an alarm. Perhaps that could be make more clear in the first sentence. Something like "OK, I will remind you with an alarm on ..."?

**Comment by anoadragon453** [comment]
I've hopefully made the text slightly clearer in https://github.com/anoadragon453/matrix-reminder-bot/commit/bec0c0cfca95b6ec2a6f9f3df8855dff8ce3a441: 

![image](https://user-images.githubusercontent.com/1342360/91672286-88d1f580-eb25-11ea-85c2-3c4263d8093d.png)

Let me know what you think :relaxed:

**Comment by anoadragon453** [comment]
Closing this for now. If you think the wording needs changes, please reopen.

**Comment by HarHarLinks** [comment]
While I understand to some extend why it is this way, I don't totally agree with the UX decision here.
- I want to set an alarm, I typed `!alarmme something something`, why does it remind me, the code agnostic user, of the alarm first instead of just being an alarm?
- Why not make the "snooze" interval (5m) configurable?

Maybe it's just because I don't see any use case you might have had in mind when designing this.

**Comment by anoadragon453** [comment]
Hmm, can you tell me what you see as the desired user interaction (maybe with an example)?

Do you mean just referring to them as "alarms" instead of reminders, without changing any other functionality?

**Comment by HarHarLinks** [comment]
I think this actually works pretty well, I would merely change the wording. To clarify: right now there is
1. one reminder: "(This reminder has an alarm. You will be reminded again in 5m. Use the !silence command to stop)."
2. the repeating alarm: "Alarm: `@me:homeserver.tld` text (Use !silence [reminder text] to silence)."

This reflects the implementation side of things, but in my opinion isn't great UX.

From my testing I think the situation already is such that the "reminder" can be `!silence`d before the first "alarm" even fires. Thus in practice and seen from the user, these fulfill the same function of "alarm". Only the consecutive messages are decluttered. However, the wording of "reminder" vs "alarm" might not be clear on that. In my opinion the wording in case of `!alarm*` should always only use alarm as to be less confusing _to the user_.
