### ISSUE TITLE
Configure timezone in config file

### ISSUE THREAD

**Issue by HarHarLinks** [anoadragon453/matrix-reminder-bot#5]
The bot will print scheduled times based on the zone that is configured on its host or container.
This can be confusing, it would be nice if it could clarify the zone when echoing times.

On top it would be great if you could clarify how to set the zone for the container. After a quick search it seems like this isn't necessarily trivial for alpine images. In fact, it may be worth considering to allow passing the timezone as a startup arg to the python script even for native installs.

**Comment by anoadragon453** [comment]
Good point, hard to notice when you live in UTC :)

I think it'd also be useful to be able to set time zones on a per-room basis. I've created an issue for that here: https://github.com/anoadragon453/matrix-reminder-bot/issues/6
