### ISSUE TITLE
Bot acts on messages that were sent before it got invited to the room

### ISSUE THREAD

**Issue by Bubu** [anoadragon453/matrix-reminder-bot#59]
When inviting the bot to a DM it tried decrypting a bunch of older messages and responded to each with 

> Unable to decrypt this message. Check whether you've chosen to only encrypt to trusted devices.

The messages (7 of them) were all about 5 days old. Maybe the bot can ignore events from before it was invited?

**Comment by Bubu** [comment]
Mh, actually this has nothing to do with encryptes messages. The bot will happily react to the last messages send before it got invited to a room in all cases.

**Comment by svierne** [comment]
@HarHarLinks I'm having the same issue. Couldn't we just drop all message events prior to the start time of the bot, e.g.

```diff
async def message(self, room: MatrixRoom, event: RoomMessageText): 
    """Callback for when a message event is received""" 
    # Ignore messages from ourselves 
    if event.sender == self.client.user: 
        return
+
+   # Ignore messages from the past
+   if self.start_time > event.server_timestamp:
+       return
```

**Comment by HarHarLinks** [comment]
> @HarHarLinks I'm having the same issue. Couldn't we just drop all message events prior to the start time of the bot, e.g.

I don't think the start time will do it, I might have started the bot weeks ago but only now invite it to the room. It should be the bot's `m.room.member` state's `origin_server_ts` which sounds well possible.
