### ISSUE TITLE
Unable to decrypt this message.

### ISSUE THREAD

**Issue by roughnecks** [anoadragon453/matrix-reminder-bot#98]
Lately I'm getting this message on a daily basis:

"Unable to decrypt this message. Check whether you've chosen to only encrypt to trusted devices."
After I send another message it fixes itself.

https://i.imgur.com/eAmlW1s.jpeg

**Comment by HarHarLinks** [comment]
Yeah I can confirm the issue. Almost feels like nio isn't sending keys frequently enough or so, but that's just a gut feeling.

**Comment by roughnecks** [comment]
Thanks for feedback.

**Comment by HarHarLinks** [comment]
I'm closing this as a duplicate of #69 which has more info.
